// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhebq0vpX4i2DqVhdOisxg9MXbtyuY9w',
    appId: '1:673437984679:web:83b6b89b119b23e6617882',
    messagingSenderId: '673437984679',
    projectId: 'trueque-tech',
    authDomain: 'trueque-tech.firebaseapp.com',
    storageBucket: 'trueque-tech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZBEWk7FW57IT-i8vQBZ5gcU9CjyUKigU',
    appId: '1:673437984679:android:a907488e4774a82a617882',
    messagingSenderId: '673437984679',
    projectId: 'trueque-tech',
    storageBucket: 'trueque-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTrhtzfpyQ_gR9hxqMEIy4m6wuZYxg98',
    appId: '1:673437984679:ios:2f9b88a2a8fbe6b5617882',
    messagingSenderId: '673437984679',
    projectId: 'trueque-tech',
    storageBucket: 'trueque-tech.appspot.com',
    iosBundleId: 'com.example.truequeTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgTrhtzfpyQ_gR9hxqMEIy4m6wuZYxg98',
    appId: '1:673437984679:ios:2f9b88a2a8fbe6b5617882',
    messagingSenderId: '673437984679',
    projectId: 'trueque-tech',
    storageBucket: 'trueque-tech.appspot.com',
    iosBundleId: 'com.example.truequeTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhebq0vpX4i2DqVhdOisxg9MXbtyuY9w',
    appId: '1:673437984679:web:a0a27a738d052b6b617882',
    messagingSenderId: '673437984679',
    projectId: 'trueque-tech',
    authDomain: 'trueque-tech.firebaseapp.com',
    storageBucket: 'trueque-tech.appspot.com',
  );
}
